### ISSUE TITLE
Hello world example?

### ISSUE THREAD

**Issue by JeysonFlores** [nesanter/chicken-bindings#1]
Hi, I was searching for Gtk bindings for Chicken Scheme and the closest thing I found was this repo.
Do you have an example about a hello world or how to manage signals, instantiate widgets etc.?

**Comment by nesanter** [comment]
Hi! This was a blast from the past -- I haven't thought about this for a while. If you give me a day or two, I'll go through my old stuff and put something together.

**Comment by JeysonFlores** [comment]
Hahaha xD It's Ok, take your time. 👍🏼

**Comment by nesanter** [comment]
I put togeter a very cursory example. Let me know if that is helpful at all. I'll probably put up some more details and a lengthier thing in the next while. :)

**Comment by JeysonFlores** [comment]
Really thanks! It works well and I'm experimenting a little bit with it. Thanks for the help!

**Comment by nesanter** [comment]
You're very welcome.
